# Generated by Django 5.2.5 on 2025-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('city', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
